# Generated by Django 3.2 on 2021-04-18 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wpp',
            options={'verbose_name_plural': 'WPPs'},
        ),
    ]
