version: "3.8"

services: 
    barata-api:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/app
        # ports:
        #     - 8000:8000
        env_file: 
            - .env
        restart: "on-failure"
        depends_on: 
            - postgres-db
        networks: 
            - barata-api
    
    postgres-db:
        image: kartoza/postgis:12.0
        ports: 
            - 5432:5432
        volumes: 
            - postgres_data:/var/lib/postgresql
        environment: 
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASS=${POSTGRES_PASS}
            - POSTGRES_DBNAME=${POSTGRES_DBNAME}
        restart: "on-failure"
        networks: 
            - barata-api
    
    barata-client:
        build:
            context: ./barata_client
            dockerfile: Dockerfile.dev
        container_name: barata_frontend
        volumes: 
            - ./app/node_modules
            - ./barata_client:/app
        depends_on: 
            - barata-api
        networks: 
            - barata-api
            
    nginx:
        restart: always
        depends_on: 
            - barata-api
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports: 
            - 8080:80
        networks: 
            - barata-api

networks: 
    barata-api:
        driver: bridge

volumes: 
    postgres_data: