# Generated by Django 3.2 on 2021-04-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='status',
            field=models.CharField(choices=[('AIS', 'AIS'), ('VMS', 'VMS'), ('NA', 'N/A')], max_length=5, verbose_name='Status'),
        ),
    ]
