# Generated by Django 3.2 on 2021-04-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpp',
            name='wpp',
            field=models.IntegerField(verbose_name='WPP Name'),
        ),
    ]
