# Generated by Django 3.2 on 2021-04-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0002_alter_wpp_wpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpp',
            name='wpp',
            field=models.IntegerField(choices=[(571, '571'), (572, '572'), (573, '573'), (711, '711'), (712, '712'), (713, '713'), (714, '714'), (715, '715'), (716, '716'), (717, '717'), (718, '718')], verbose_name='WPP Name'),
        ),
    ]
